import { Prudact } from './Prudact';

export const productsList: Prudact[] = [
  { id: 1, name: 'Dog Poop', image: '', price: 3500 },
  { id: 2, name: 'Horse Poop', image: '', price: 50 },
  { id: 2, name: 'Cat Poop', image: '', price: 350 },
  { id: 4, name: 'Man Poop', image: '', price: 3330 },
  { id: 5, name: 'bird Poop', image: '', price: 30 },
  { id: 6, name: 'big Poop', image: '', price: 3660 },
  { id: 7, name: 'Smalg Poop', image: '', price: 3770 },
  { id: 8, name: 'safdad Poop', image: '', price: 3660 },
  { id: 9, name: 'dsf Poop', image: '', price: 3570 },
  { id: 10, name: 'dsf Poop', image: '', price: 3570 },
  { id: 11, name: 'dsf Poop', image: '', price: 3570 },
  { id: 12, name: 'dsf Poop', image: '', price: 3570 },
  { id: 13, name: 'dsf Poop', image: '', price: 3570 },
  { id: 14, name: 'dsf Poop', image: '', price: 3570 },
  { id: 15, name: 'dsf Poop', image: '', price: 3570 },
  { id: 16, name: 'dsf Poop', image: '', price: 3570 },
  { id: 17, name: 'dsf Poop', image: '', price: 3570 },
  { id: 18, name: 'dsf Poop', image: '', price: 3570 },
  { id: 19, name: 'dsf Poop', image: '', price: 3570 },
  { id: 20, name: 'dsf Poop', image: '', price: 3570 },
  { id: 21, name: 'dsf Poop', image: '', price: 3570 },
  { id: 22, name: 'dsf Poop', image: '', price: 3570 },
  { id: 23, name: 'dsf Poop', image: '', price: 3570 },
  { id: 24, name: 'dsf Poop', image: '', price: 3570 },
  { id: 25, name: 'dsf Poop', image: '', price: 3570 },
  { id: 26, name: 'dsf Poop', image: '', price: 3570 },
  { id: 27, name: 'dsf Poop', image: '', price: 3570 },
];
